---
version: 0.2

environment_variables:
  plaintext:
    PACKER_VERSION: "0.12.3"
    PACKER_TEMPLATE: "centos-6.json"
    TARGET_REGION: "ap-northeast-1"
    AMI_MODIFIER: "create-custom-ami-codebuild"

phases:
  pre_build:
    commands:
      - cd aws/ami
      # Install Packer
      - echo "Install packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      # Install jq
      - echo "Install jq"
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      # Validate packer template
      - pwd
      - ls -al
      - echo "Validate packer template json"
      - ./packer validate ${PACKER_TEMPLATE}
  build:
    commands:
      - echo "Set AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region ${TARGET_REGION}
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - cat aws_credentials.json
      - ./packer build -var "ami_modified_by=${AMI_MODIFIER}" -var-file=aws_credentials.json ${PACKER_TEMPLATE}
  post_build:
    commands:
      - echo "Finish the build with packer `date`"
