---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Install jq"
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validate packer template json"
      - cd aws/ami && ../../packer validate centos-6.json
  build:
    commands:
      - echo "Set AWS credentials"
      - cd ../../
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region ap-northeast-1
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Build centos-6.json"
      - cat aws_credentials.json
      - cd aws/ami && ../../packer build -var-file=../../aws_credentials.json centos-6.json
  post_build:
    commands:
      - echo "Finish the build with packer `date`"
